#!/usr/bin/env bash
set -euo pipefail

system=${1:-x86_64-linux}

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$script_dir/.."

./scripts/build-release-tarball "$system"

hash=$(nix hash file --sri --type sha256 "releases/${system}.tar.gz")
sed -i "s|\"${system}\" = \"sha256-[^\"]*\";|\"${system}\" = \"${hash}\";|" ./nix/prebuilt-hashes.nix
