name: Release
on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Build for ${{ matrix.system }}
        run: scripts/build-release-tarball ${{ matrix.system }}
      - name: Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: releases/*.tar.gz
